Failure # 1 (occurred at 2023-07-25_14-27-55)
[36mray::A2C.train()[39m (pid=63336, ip=127.0.0.1, actor_id=21cb20a1093ac3ca2403129a01000000, repr=A2C)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 389, in train
    raise skipped from exception_cause(skipped)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 386, in train
    result = self.step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 803, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2853, in _run_one_training_iteration
    results = self.training_step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/a2c/a2c.py", line 174, in training_step
    return Algorithm.training_step(self)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 1378, in training_step
    train_batch = synchronous_parallel_sample(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(IndexError): [36mray::RolloutWorker.apply()[39m (pid=63337, ip=127.0.0.1, actor_id=b8c16cea8e9d400fd24a0e5801000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x13f9451f0>)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 185, in apply
    raise e
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/env/vector_env.py", line 464, in send_actions
    ) = self.vector_env.vector_step(action_vector)
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/env/vector_env.py", line 360, in vector_step
    raise e
  File "/Users/akest/miniforge3/envs/conda_env/lib/python3.9/site-packages/ray/rllib/env/vector_env.py", line 353, in vector_step
    results = self.envs[i].step(actions[i])
  File "/Users/akest/Desktop/Innostage/main_work/qweqwe/eplus/data_center_env.py", line 277, in step
    next_state = self.reset()
  File "/Users/akest/Desktop/Innostage/main_work/qweqwe/eplus/data_center_env.py", line 317, in reset
    next_state = np.array(self.construct_next_state())
  File "/Users/akest/Desktop/Innostage/main_work/qweqwe/eplus/data_center_env.py", line 250, in construct_next_state
    res = [self.outputs[i] for i in [2, 6, 10]]
  File "/Users/akest/Desktop/Innostage/main_work/qweqwe/eplus/data_center_env.py", line 250, in <listcomp>
    res = [self.outputs[i] for i in [2, 6, 10]]
IndexError: list index out of range
